gog_pw_cache_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: GogPwCacheBundle:Default:index }

nocache:
    pattern: /nocache
    defaults: { _controller: GogPwCacheBundle:Cache:nocache }

memcache:
    pattern: /memcache
    defaults: { _controller: GogPwCacheBundle:Cache:memcache }

xcache:
    pattern: /xcache
    defaults: { _controller: GogPwCacheBundle:Cache:xcache }

varnish:
    pattern: /varnish
    defaults: { _controller: GogPwCacheBundle:Cache:varnish }

esi:
    pattern:  /esi
    defaults: { _controller: GogPwCacheBundle:Cache:esi }

esi_include:
    pattern:  /esi_include
    defaults: { _controller: GogPwCacheBundle:Cache:esiInclude }

