gog_pw_cache_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: GogPwCacheBundle:Default:index }

nocache:
    pattern: /nocache
    defaults: { _controller: GogPwCacheBundle:Cache:nocache }

memcache:
    pattern: /memcache
    defaults: { _controller: GogPwCacheBundle:Cache:memcache }
